---
vm_types:
- name: micro
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: medium_2_4
- name: small
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: medium_2_8
- name: medium
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: medium_4_8
- name: large
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: medium_4_16
- name: mlarge
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: medium_4_16rng
- name: xlarge
  cloud_properties:
    boot_from_volume: false
    instance_type: medium_4_16rng_ld
- name: 2xlarge
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: extralarge_8_16
- name: 4xlarge
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: extralarge_8_16
- name: 10xlarge
  cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: extralarge_16_32

compilation:
  network: compilation
  reuse_compilation_vms: true
  vm_type: small
  workers: 5

disk_types:
- disk_size: 1024
  name: hdd_1gb
- disk_size: 2000
  name: hdd_2gb
- disk_size: 4000
  name: hdd_4gb
- disk_size: 6000
  name: hdd_6gb
- disk_size: 8000
  name: hdd_8gb
- disk_size: 10000
  name: hdd_10gb
- disk_size: 20000
  name: hdd_20gb
- disk_size: 40000
  name: hdd_40gb
- disk_size: 60000
  name: hdd_60gb
- disk_size: 80000
  name: hdd_80gb
- disk_size: 100000
  name: hdd_100gb
- disk_size: 200000
  name: hdd_200gb
- disk_size: 400000
  name: hdd_400gb
- disk_size: 600000
  name: hdd_600gb
- disk_size: 800000
  name: hdd_800gb
- disk_size: 1000000
  name: hdd_1tb
- disk_size: 2000000
  name: hdd_2tb
- disk_size: 4000000
  name: hdd_4tb
- disk_size: 6000000
  name: hdd_6tb
- disk_size: 8000000
  name: hdd_8tb

networks:
- name: compilation
  type: dynamic
  subnets:
  - cloud_properties:
      net_id: fd602ea5-2a2c-410f-b7f4-50b23cc901dc
      security_groups:
      - service-fabrik-bosh-services
    gateway: 10.11.255.65
    range: 10.11.255.64/26

- name: service_fabrik
  type: manual
  subnets:
  - cloud_properties:
      net_id: 6bfbdf39-4a91-4d23-9093-dde1d6924791
      security_groups:
      - service-fabrik
    dns:
    - 172.18.4.23
    - 172.18.4.24
    gateway: 10.11.252.1
    range: 10.11.252.0/24
    reserved:
    - 10.11.252.1
    - 10.11.252.255
    static:
    - 10.11.252.2 - 10.11.252.254
  - cloud_properties:
      net_id: fd602ea5-2a2c-410f-b7f4-50b23cc901dc
      security_groups:
      - service-fabrik
    dns:
    - 172.18.4.23
    - 172.18.4.24
    gateway: 10.11.253.1
    range: 10.11.253.0/24
    reserved:
    - 10.11.253.1
    - 10.11.253.255
    static:
    - 10.11.253.2 - 10.11.253.254
  - cloud_properties:
      net_id: 0c746dac-b57b-41c4-8e92-8063ccc8493e
      security_groups:
      - service-fabrik
    dns:
    - 172.18.4.23
    - 172.18.4.24
    gateway: 10.11.254.1
    range: 10.11.254.0/24
    reserved:
    - 10.11.254.1
    - 10.11.254.255
    static:
    - 10.11.254.2 - 10.11.254.254

- name: default
  type: manual
  subnets:
  - cloud_properties:
      net_id: 6bfbdf39-4a91-4d23-9093-dde1d6924791
      security_groups:
      - service-fabrik-bosh-services
    dns:
    - 172.18.4.23
    - 172.18.4.24
    gateway: 10.11.0.1
    range: 10.11.0.0/18
    reserved:
    - 10.11.0.1
    - 10.11.0.2
    - 10.11.0.3
    - 10.11.0.4
    - 10.11.63.255
  - cloud_properties:
      net_id: fd602ea5-2a2c-410f-b7f4-50b23cc901dc
      security_groups:
      - service-fabrik-bosh-services
    dns:
    - 172.18.4.23
    - 172.18.4.24
    gateway: 10.11.64.1
    range: 10.11.64.0/18
    reserved:
    - 10.11.64.1
    - 10.11.64.2
    - 10.11.64.3
    - 10.11.64.4
    - 10.11.127.255
  - cloud_properties:
      net_id: 0c746dac-b57b-41c4-8e92-8063ccc8493e
      security_groups:
      - service-fabrik-bosh-services
    dns:
    - 172.18.4.23
    - 172.18.4.24
    gateway: 10.11.128.1
    range: 10.11.128.0/18
    reserved:
    - 10.11.128.1
    - 10.11.128.2
    - 10.11.128.3
    - 10.11.128.4
    - 10.11.128.255